trigger:
  branches:
    include:
    - develop

variables:
  USER: ubuntu
  BRANCH_NAME: develop
  DOCKER_REPO: < Docker Repository >
  DOCKER_IMAGE: < Docker Image >
  PORT: < PORT APP >
  GIT_REPOSITORY: < NAME GIT REPOSITORY >

stages:
- stage: Get-Last-Changes
  displayName: Get Last Changes
  jobs:  
  - job: Get-Last-Changes
    displayName: Get-Last-Changes
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: self
      clean: true

    - script: |
        git checkout $(BRANCH_NAME)
        git pull
      displayName: "Change Branch and Get Last Changes" 

stages:
- stage: BuildPush
  displayName: Build and push App
  jobs:  
  - job: BuildPush
    displayName: BuildPush
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - script: |
        docker build -t $(DOCKER_REPOSITORY)/$(NAME_REPO):DEV-$(COMMIT_ID) .
        docker push $(DOCKER_REPOSITORY)/$(NAME_REPO):DEV-$(COMMIT_ID)
        docker rmi $(DOCKER_REPOSITORY)/$(NAME_REPO):DEV-$(COMMIT_ID)
        TAG=echo "$(git log -1 --pretty=format:"%h")""
        rm -fd ../$(GIT_REPOSITORY)
      displayName: "Build and Push Docker" 

    - script: |
        sshpass -p $(secretPASS_DEV) ssh $(USER)@$(secretIP_PUB_DEV) './deploy.sh $(DOCKER_REPO) $(DOCKER_IMAGE) $TAG $(PORT) '
      displayName: "Deploy Virtual Machine Environment Development"