trigger:
  branches:
    include:
    - feature/*

variables:
  BRANCH_NAME: $[replace(variables['Build.SourceBranchName'], 'refs/heads/', '')]

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true

- script: |
    git checkout '$(BRANCH_NAME)'
    git pull
    git merge develop
    git add .
    git commit -m 'Merge branch $(BRANCH_NAME)'
    git push
  displayName: 'Reintegration Dev Environments'